### ISSUE TITLE
疯狂点击名片，导致无法识别

### ISSUE THREAD

**Issue by MomentDerek** [YuehaiTeam/cocogoat#1]
最后会显示识别失败
![image](https://user-images.githubusercontent.com/40252940/157473643-15325290-cab4-405d-9beb-f22fdd98ecaa.png)

**Comment by xytoki** [comment]
目前是暂时没考虑带名片的页面的，因为这部分不会有隐藏、有明显的进度，数量也不会太大。最近暂时比较忙，等有空了我还是加上。

**Comment by xytoki** [comment]
已经可以正常识别和滚动了。就是目前没有直接把名片这一栏过滤掉，还是会提示失败。
