### ISSUE TITLE
从2.7更新之后，一直存在同步失败的问题

### ISSUE THREAD

**Issue by DaftDogeee** [YuehaiTeam/cocogoat#10]
是我的网络原因吗，还是作者在维护服务器？

**Comment by xytoki** [comment]
麻烦提供一下同步失败的状态截图，服务器维护挺早就结束了

**Comment by DaftDogeee** [comment]
如图所示~

![Snipaste_2022-06-01_00-18-11](https://user-images.githubusercontent.com/49086184/171326609-0cd285c2-a431-4eaf-96a4-8de6f0df9319.png)

**Comment by xytoki** [comment]
你首页能看到暂停服务的公告吗 有就是浏览器可能缓存了不该缓存的东西 没有就是网络问题概率比较大
麻烦在设置里提交一下反馈然后在这里留一下反馈ID 我看看能不能查出来

**Comment by DaftDogeee** [comment]
目前首页截图如下：
![Snipaste_2022-06-01_00-45-13](https://user-images.githubusercontent.com/49086184/171329508-85accbe6-1385-449d-8775-6ea46b64de9e.png)

多谢多谢~

**Comment by xytoki** [comment]
![image](https://user-images.githubusercontent.com/7547189/171329778-1c29564f-e3e7-4a8c-9746-5656cd0bcd3a.png)
麻烦在这里提交一下反馈，我这边可能要看一下错误日志才方便，感谢！

**Comment by DaftDogeee** [comment]
已反馈，ID: 3a3805ad3de84b6099969f53f5f94b35

**Comment by xytoki** [comment]
看了一下日志，可能是国外api中转服务器的状态没有同步过来。
尝试修复了，刷新一下试试，

**Comment by DaftDogeee** [comment]
可以啦，谢谢大佬~
