### ISSUE TITLE
独立悬浮窗 zhiqiong-1.0.8 无法安装

### ISSUE THREAD

**Issue by tommynanny** [YuehaiTeam/cocogoat#12]
请问有绿色版么 这个无法安装欸
![image](https://user-images.githubusercontent.com/22390882/179405294-f7fb1c89-f43d-4cca-9ebd-cb3c4195f85a.png)

**Comment by xytoki** [comment]
因为需要调整部分系统设置，所以没有绿色版。
这个提示可以自测在任意cmd窗口内输入powershell，自行修复到没有任何错误提示即可安装，每个电脑遇到的问题可能不一样。

顺便，这个问题应该移到 https://github.com/YuehaiTeam/zhiqiong-uwp/issues
