### ISSUE TITLE
“PC端更新包列表”无法获取更新后的游戏包体

### ISSUE THREAD

**Issue by CRZZA** [YuehaiTeam/cocogoat#121]
### PC 端更新包列表工具
无法获取到 _2024/06/17_ miHoYo 停止维护旧版API后的新游戏包体
_/旧版API仍然可以获取到旧版游戏的包体，但无法获取在更换API后的新包体_
目前受影响的游戏：崩坏：星穹铁道_2.3版本(预下载)
请尽快更新到**新版API**

**Comment by Wujusiji** [comment]
好像修好了，xqtd可以下载2.3版本了

**Comment by xytoki** [comment]
已更新到hyp api。
