### ISSUE TITLE
网页版一直加载 打不开 持续半个月了

### ISSUE THREAD

**Issue by Belle0602Xin** [YuehaiTeam/cocogoat#128]
![Screenshot 2024-07-07 at 9 10 55 AM](https://github.com/YuehaiTeam/cocogoat/assets/134656861/9c5a9794-76cf-4f94-a730-a31e2fb29b41)
坐标美国 Chrome QQ浏览器 Safari 微信默认浏览器 都试过了一直显示加载中打不开 VPN翻墙回国也不好使
求解决方式 离线模式没弄明白

**Comment by Belle0602Xin** [comment]
求解决方式 离线模式没弄明白

**Comment by MeteorTan** [comment]
![图片](https://github.com/user-attachments/assets/610674c7-3e99-476b-9d5a-02f1b57dcfc6)
 可能可以检查下这个接口
