### ISSUE TITLE
登录账号失败

### ISSUE THREAD

**Issue by boxsnake** [YuehaiTeam/cocogoat#133]
登录账号时报错：
![image](https://github.com/user-attachments/assets/9803e233-ed20-458e-af5b-4bda39ff4741)
![image](https://github.com/user-attachments/assets/8cb0dbc2-c02d-46de-a323-c028d931b180)

**Comment by kent52712** [comment]
+1  椰羊云/onedrive都不行了

**Comment by xytoki** [comment]
cdn回源超时，调整了一下，再试试？近期准备更换cdn了，如果还是有问题就提前换

**Comment by boxsnake** [comment]
Resolved.
