### ISSUE TITLE
无法仅查看“天地万象”分类的成就

### ISSUE THREAD

**Issue by chenjunyu19** [YuehaiTeam/cocogoat#137]
## 问题和现象

PR <https://github.com/YuehaiTeam/cocogoat/pull/119> 引入了搜索所有成就的功能，但同时导致默认情况下会展示所有成就。就算主动点击“天地万象”分类，也无法仅查看该分类下的成就。

## 临时解决方案

用户可以手动路由到 `/achievement/wonders-of-the-world` 来访问“天地万象”分类。

<https://cocogoat.work/achievement/wonders-of-the-world>

## 可能的解决方案

增加一个虚拟分类“所有”或“全部”，然后使该分类成为 `/achievement` 路由的对应分类，再使 `/achievement/wonders-of-the-world` 路由对应“天地万象”分类。

## 相关 Issues

- <https://github.com/YuehaiTeam/cocogoat/issues/140>
- <https://github.com/YuehaiTeam/cocogoat/issues/141>
- <https://github.com/YuehaiTeam/cocogoat/issues/143>
- <https://github.com/YuehaiTeam/cocogoat/issues/149>
- <https://github.com/YuehaiTeam/cocogoat/issues/153>

**Comment by MeteorTan** [comment]
这样确实更好

**Comment by chenjunyu19** [comment]
@xytoki 可以关闭上面提到的相关 Issues 了。
