### ISSUE TITLE
5.0新成就主页提示已更新，但实际使用时没有

### ISSUE THREAD

**Issue by EZio888** [YuehaiTeam/cocogoat#138]
![image](https://github.com/user-attachments/assets/b03e74f6-0fcc-48b3-8381-705d021a99f5)

**Comment by xytoki** [comment]
后续如果有再遇到，设置里清一下本地数据看看？目前公告和数据不是走同一个渠道下发的

**Comment by jiongjiongJOJO** [comment]
![image](https://github.com/user-attachments/assets/f87ffb67-c103-4a19-99e6-f705b606dc4f)

测试了多轮下来，发现勾选Service Worker后可以恢复正常，开启了禁用缓存也不行，不太懂这里面的东西，给个参考吧。感觉是资源优先本地了。4044.xxxxx.js 加载的一直是上个版本的文件。

@xytoki
