### ISSUE TITLE
能不能出个看b站视频的xbox悬浮窗

### ISSUE THREAD

**Issue by Ira125** [YuehaiTeam/cocogoat#14]
用手机看攻略跟跑很不方便,能不能出个看b站视频的xbox悬浮窗?

**Comment by xytoki** [comment]
windows自带商店有个app叫gamebar browser，是浏览器悬浮窗，应该够用。

**Comment by Ira125** [comment]
试了一下不太行,这个app缩到最小也要占据小半个笔记本屏幕,而且不只是bug还是这浏览器就这样,网页上所有可点击的按钮都没反应
