### ISSUE TITLE
Chrome中无法加载页面

### ISSUE THREAD

**Issue by stevenimd** [YuehaiTeam/cocogoat#145]
不知道是不是更新了最新Chrome的原故，打开时如下图。Edge中正常
![1](https://github.com/user-attachments/assets/be92d027-87d9-4dbe-acc0-0583713ce763)

**Comment by stevenimd** [comment]
已解决。

**Comment by LukeChen-j** [comment]
请问你是怎么解决的，我遇到的问题貌似和你一样。
