### ISSUE TITLE
honeyhunterworld 链接变更

### ISSUE THREAD

**Issue by psi-cmd** [YuehaiTeam/cocogoat#16]
honeyhunterworld 站内词条 url 路径发生变更，原链接被重定向至主页，可考虑批量修正一下。

如 <https://genshin.honeyhunterworld.com/db/achiev/achiev_80127/?lang=CHS> 
-> <https://genshin.honeyhunterworld.com/a_80127/?lang=CHS>

站内词条中任务被重新分类，ID 发生改变，需要重新抓取链接。

**Comment by xytoki** [comment]
已修，以及链接都是直接构造的，暂时不存在抓取，任务链接似乎目前没有明显的和分类的关系，测了一部分都能构造出来，先这样放着，如果还有问题再reopen。
