### ISSUE TITLE
3.0成就未全部列入，已发现的如3.0每日委托成就不全

### ISSUE THREAD

**Issue by Koki-plus** [YuehaiTeam/cocogoat#18]
[https://www.gamersky.com/handbook/202209/1517023.shtml](url)

**Comment by xytoki** [comment]
麻烦给下具体名字，这个链接里的我都直接查过了都有。
可作参考的成就表：https://docs.qq.com/sheet/DS01hbnZwZm5KVnBB

**Comment by Koki-plus** [comment]
没想到回复得这么快哈哈，我也核查了一下，发现的确有，但分类没有被分为每日委托成就。我在网站里查看3.0的每日委托成就只看到了3个相关成就，以为是漏掉了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YuehaiTeam/cocogoat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月26日(星期一) 下午4:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YuehaiTeam/cocogoat] 3.0成就未全部列入，已发现的如3.0每日委托成就不全 (Issue #18)





 
麻烦给下具体名字，这个链接里的我都直接查过了都有。
 可作参考的成就表：https://docs.qq.com/sheet/DWHlQV2dBQ1RqY29q

**Comment by xytoki** [comment]
分类目前看来是数据源的成就关联任务部分格式又有变，已经在看了（
如果没法兼容可能会改成手动标。

**Comment by Koki-plus** [comment]
辛苦了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YuehaiTeam/cocogoat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月26日(星期一) 下午4:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YuehaiTeam/cocogoat] 3.0成就未全部列入，已发现的如3.0每日委托成就不全 (Issue #18)





 
分类目前看来是数据源的成就关联任务部分格式又有变，已经在看了（
 如果没法兼容可能会改成手动标。
