### ISSUE TITLE
“志琼 米游社地图插件”无法使用，且QQ群已满无法加入

### ISSUE THREAD

**Issue by LeapRay** [YuehaiTeam/cocogoat#19]
无论是“独立悬浮窗 Game Bar悬浮窗”还是“网页版插件 安装油猴脚本”，均在完整安装、原神正常运行、椰羊 霜华插件授权后提示“未检测到原神窗口”。
同时，QQ群已满2000人，无法加入。

**Comment by xytoki** [comment]
近期cvautotrack dll有大版本更新，志琼在适配，等更新后如果还有问题可以去志琼的repo提。
