### ISSUE TITLE
加载进度卡在 66.66%

### ISSUE THREAD

**Issue by qiutongxue** [YuehaiTeam/cocogoat#23]
如图，点击右上角的识别后就卡这了

![image](https://user-images.githubusercontent.com/53330358/195800233-351cf1b4-c882-440f-b820-b33615515538.png)

**Comment by xytoki** [comment]
卡66看起来是有一个资源文件下载卡住了或者失败了，可能需要看看Network里的情况

**Comment by qiutongxue** [comment]
> 卡66看起来是有一个资源文件下载卡住了或者失败了，可能需要看看Network里的情况

现在突然又好了^^
