### ISSUE TITLE
椰羊网一直在加载中打不开是咋回事呀

### ISSUE THREAD

**Issue by baek2me** [YuehaiTeam/cocogoat#29]
![捕获](https://user-images.githubusercontent.com/120249205/206848728-6c2cda2b-2087-4e4f-b169-a7631416c3b3.PNG)
截了张图不知道能不能看见，昨晚想打开看看成就的时候就一直在显示加载中打不开
用的Chrome浏览器

**Comment by xytoki** [comment]
按F12或者右键审查元素，点Console，截图发一下

**Comment by baek2me** [comment]
你好！这个是我按F12之后出来的界面


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YuehaiTeam/cocogoat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月10日(星期六) 晚上7:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YuehaiTeam/cocogoat] 椰羊网一直在加载中打不开是咋回事呀 (Issue #29)





 
按F12或者右键审查元素，点Console，截图发一下

**Comment by xytoki** [comment]
您可能需要到github回复，邮件回复并没有附带截图

**Comment by baek2me** [comment]
我换了个方式，麻烦你看看这次有嘛
大概是因为上一封邮件添加的是附件





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YuehaiTeam/cocogoat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月10日(星期六) 晚上8:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YuehaiTeam/cocogoat] 椰羊网一直在加载中打不开是咋回事呀 (Issue #29)





 
您可能需要到github回复，邮件回复并没有附带截图

**Comment by baek2me** [comment]
![捕获](https://user-images.githubusercontent.com/120249205/206855359-e5c9abcc-0e2a-4426-abd3-940f3bafe69e.PNG)

**Comment by baek2me** [comment]
我在github上回复了截图啦




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YuehaiTeam/cocogoat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月10日(星期六) 晚上8:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YuehaiTeam/cocogoat] 椰羊网一直在加载中打不开是咋回事呀 (Issue #29)





 
您可能需要到github回复，邮件回复并没有附带截图

**Comment by xytoki** [comment]
麻烦在F12里切换到Network，然后按刷新，再截一下图，目前看来可能有一定得网络问题因素

**Comment by baek2me** [comment]
![屏幕截图 2022-12-10 204652](https://user-images.githubusercontent.com/120249205/206855869-1e5ea5a1-08de-49b3-9634-72729ace5641.png)
这个是新的截图

**Comment by xytoki** [comment]
https://hidden/index.json
您能正常访问这个链接吗

**Comment by baek2me** [comment]
不能诶，我点击链接之后只显示了一串代码

**Comment by xytoki** [comment]
您能复制一下代码吗，我确认一下是不是正常的

**Comment by baek2me** [comment]
["10l05ds",["https://77.xyget.cn/static/js/vendors.03e98700.js","https://77.xyget.cn/static/js/app.ee536116.js"],["https://77.xyget.cn/static/css/app.5b81ac41.css"],"static/sw/3d4a7e98.json"]

**Comment by xytoki** [comment]
代码内容是符合预期的，您试试在这里勾选一下禁用缓存然后刷新看看呢
![Snipaste_2022-12-10_20-59-02](https://user-images.githubusercontent.com/7547189/206856348-a291dd22-8725-44d0-b862-956459bb1c46.png)

**Comment by baek2me** [comment]
可以访问了！谢谢大佬！
