### ISSUE TITLE
导出的成就信息中时间格式不正确

### ISSUE THREAD

**Issue by Lightczx** [YuehaiTeam/cocogoat#4]
详细信息：
https://github.com/DGP-Studio/Snap.Genshin/issues/257#issuecomment-1098783080

**Comment by xytoki** [comment]
```js
new Date("9999").toISOString()
// '9999-01-01T00:00:00.000Z'
new Date("10001").toISOString()
// '+010000-12-31T16:00:00.000Z'
new Date('+010000-12-31T16:00:00.000Z')
// Mon Jan 01 10001 00:00:00 GMT+0800 (中国标准时间)
```
这个东西本质是OCR扫错扫出了五位数年份。然后ISO 8601对大于9999的年份的处理就是这样的（五位数年份前面加加号），所以可能是SG那边用的日期库没有识别这个大于9999年的格式。

我再处理一下把超过9999的年份全部清理掉把。

**Comment by xytoki** [comment]
推了一个migrate上线，https://github.com/YuehaiTeam/cocogoat/commit/6ca852102c67b30f4f9213cad76ea3090b2ca5a0
看看行不行，不行再继续修，现在是把五位数的年份全部尝试纠正，然后不符合纠正规则的就改成今年

**Comment by Lightczx** [comment]
我自己测试是没问题了

**Comment by xytoki** [comment]
那可以先close，后续再有相关问题再reopen（

**Comment by xytoki** [comment]
另外在 https://github.com/YuehaiTeam/cocogoat/commit/0c2b5867e075cab8a62a138fadd8c37dc481c035 做了一下复制到剪贴板并自动调用SG的Url Scheme导入（

**Comment by Lightczx** [comment]
> 另外在 [0c2b586](https://github.com/YuehaiTeam/cocogoat/commit/0c2b5867e075cab8a62a138fadd8c37dc481c035) 做了一下复制到剪贴板并自动调用SG的Url Scheme导入（

Thx a lot

**Comment by Lightczx** [comment]
等等
https://github.com/YuehaiTeam/cocogoat/blob/0c2b5867e075cab8a62a138fadd8c37dc481c035/src/views/Achievement/useExport.ts#L45

此处的格式需要字段名称为 timestamp (ignorecase)

SG使用的数据模型可以在这里查看
https://github.com/DGP-Studio/Snap.Genshin/blob/main/DGP.Genshin/DataModel/Achievement/IdTimeStamp.cs

**Comment by xytoki** [comment]
修了修了（ https://github.com/YuehaiTeam/cocogoat/commit/293e396ffba2b748e04b2067ab8b925b54ced87d ）

**Comment by Lightczx** [comment]
看了一下
是因为 C# 的 DateTime 本身不支持大于等于10000的年份
https://docs.microsoft.com/zh-cn/dotnet/api/system.datetime.maxvalue?f1url=%3FappId%3DDev16IDEF1%26l%3DZH-CN%26k%3Dk(System.DateTime.MaxValue)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=net-6.0#--
