### ISSUE TITLE
无法扫描成就

### ISSUE THREAD

**Issue by zlrnx** [YuehaiTeam/cocogoat#62]
我的椰羊无法扫描成就，之前用过插件也都齐全，但一直提示初始化，加载不了
![批注 2023-12-30 075823](https://github.com/YuehaiTeam/cocogoat/assets/155202586/4161d3fd-3a58-4715-ac6b-6e00bd7eb1e5)

**Comment by zlrnx** [comment]
日志反馈不上去，环境监测没问题
![批注 2023-12-30 081620](https://github.com/YuehaiTeam/cocogoat/assets/155202586/7e83aad2-9d2b-49f7-8042-7b3d525a000f)

**Comment by metaliguri** [comment]
我也遇到了同样的问题，通过 Chrome 控制台发现这个链接，服务器返回了 502 Bad gateway 错误
`https://77.cocogoat.work/sigh/api/0/envelope/?f9f3***c6_key=****&f9f3***dc6_version=7`
希望开发者可以尽快修复这个问题

**Comment by zlrnx** [comment]
很离谱，但是成就都还是最新的，也能手动勾选和查询，就是无法OCR识别

**Comment by 1sunxiaoshou** [comment]
我也是，一模一样的 问题

**Comment by ZM-J** [comment]
F12 报错信息：

![image](https://github.com/YuehaiTeam/cocogoat/assets/21689514/d075ee59-e0b7-488f-906b-50cf12cde121)

看上去是某个 WASM 的神奇问题

**Comment by luoshui1** [comment]
我也遇到了，在网页和本地都无法打开，反馈问题也显示错误，最难受的还是数据丢失了。现在通过换浏览器解决了。

**Comment by zlrnx** [comment]
我换浏览器也解决不了啊

**Comment by conglinyizhi** [comment]
> 我换浏览器也解决不了啊

现在我们似乎除了等待 issue 回复，没收其他任何办法联系项目所有者

**Comment by xytoki** [comment]
理论已修复，还有问题的用户可以在设置-环境检测选择 清空本地资源 后重试，issue先关闭，如果有再遇到可以重新提一个

![image](https://github.com/YuehaiTeam/cocogoat/assets/7547189/ff7dd3b2-860a-42af-a592-bf52002c0999)

**Comment by zlrnx** [comment]
好了，感谢
