### ISSUE TITLE
无法找到成就：无影的塞谟奈

### ISSUE THREAD

**Issue by yjh8144** [YuehaiTeam/cocogoat#64]
无法找到成就：无影的塞谟奈
如下图：
<img width="1165" alt="屏幕截图 2023-12-31 035130" src="https://github.com/YuehaiTeam/cocogoat/assets/154310452/544ce66e-34c2-41d3-ac4a-ea0857c60be3">
![5ff49b65076ea15d673a58c12b47f48](https://github.com/YuehaiTeam/cocogoat/assets/154310452/5bc59047-b09a-43d5-8404-5b8186a97522)

**Comment by xytoki** [comment]
这个搜索目前不是全局的，只会搜索你选中的分类，约等于默认只搜天地万象
