### ISSUE TITLE
识别成就时，应用初始化开始后就一直没反应

### ISSUE THREAD

**Issue by Shzkai** [YuehaiTeam/cocogoat#69]
<img width="1280" alt="屏幕截图 2024-01-11 191142" src="https://github.com/YuehaiTeam/cocogoat/assets/156313143/a382b81e-1ef0-4999-8aaa-16c86e2dbbda">
识别成就时，再这个界面后就没有反应了

**Comment by Guoyh1212** [comment]
解决了吗，我也一样

**Comment by ScryAbu** [comment]
据说换浏览器可以解决 我本地只有Edge和Chrome 都不行 据说火狐360啥的可以

**Comment by chenjunyu19** [comment]
根据 <https://github.com/YuehaiTeam/cocogoat/commit/7790b94d8720b4703674b5c5f16e000cba7643de>，问题现在应该已经解决。如果仍不能正常加载，则需要清空 `cocogoat.work` 的站点数据，或者在 JavaScript 控制台中执行下面的代码来清空缓存存储。

```javascript
caches.keys().then((keys) => Promise.all(
    keys.map((key) => caches.delete(key))
))
```

**Comment by wistfate** [comment]
清理数据后就解决了😮

**Comment by xytoki** [comment]
理论已修复，还有问题的用户可以在设置-环境检测选择 清空本地资源 后重试，issue先关闭，如果有再遇到可以重新提一个

![image](https://github.com/YuehaiTeam/cocogoat/assets/7547189/ff7dd3b2-860a-42af-a592-bf52002c0999)
