### ISSUE TITLE
似乎过滤器每日委托选项只能过滤出2个了？

### ISSUE THREAD

**Issue by DaftDogeee** [YuehaiTeam/cocogoat#7]
前一阵还能过滤出很多个每日委托，现在为什么只有2个了呀

![Snipaste_2022-05-10_01-08-35](https://user-images.githubusercontent.com/49086184/167546648-ec8a8699-513f-4390-9944-258d81a4b3fc.png)

**Comment by xytoki** [comment]
是解包数据改版我没发现导致的，已经修了，看看还有没有少，如果还有少任务的话可以reopen
