### ISSUE TITLE
最终枫达海，三个成就全选，成就总数会比游戏内多两个赶快修复吧

### ISSUE THREAD

**Issue by f16199** [YuehaiTeam/cocogoat#76]
![QQ截图20240205095802](https://github.com/YuehaiTeam/cocogoat/assets/158979593/3f709599-163e-4003-af35-4f82c65a3b6e)
看图

**Comment by JiuZ-Chn** [comment]
这个成就在游戏里就是可以获得3次的

**Comment by f16199** [comment]
但是选了之后在这个网页上就多出来两个成就数,以前是没有问题的,但是在游戏上个版本就出现问题了

**Comment by dudulu777** [comment]
你别吓我啊，我三个全勾上数量刚刚好
