### ISSUE TITLE
卡里米之蕈兽和当财运来敲门这两个成就不在每日委托分类中

### ISSUE THREAD

**Issue by Ireeul** [YuehaiTeam/cocogoat#82]
如题，这两个成就是通过3.0版本每日委托达成的，但是没有被归类在每日委托标签中
![屏幕截图 2024-02-14 160355](https://github.com/YuehaiTeam/cocogoat/assets/150488267/f901c1dd-456e-4faf-b0b1-73d8d1f98032)
![屏幕截图 2024-02-14 160427](https://github.com/YuehaiTeam/cocogoat/assets/150488267/0f797ac3-5cb4-46b0-95fe-b1f2808123ba)
![屏幕截图 2024-02-14 160439](https://github.com/YuehaiTeam/cocogoat/assets/150488267/a8af49e3-88d0-4c63-9b89-4780bc36762f)

**Comment by gotofandian** [comment]
还有2.0的同心训练家？和3.0的推分算数原理也不在椰羊的每日分类里
