### ISSUE TITLE
关于网页版圣遗物识别按钮为不可点击问题

### ISSUE THREAD

**Issue by DarkPocket** [YuehaiTeam/cocogoat#9]
https://cocogoat.work/artifact  ，识别按钮不可点击是功能不支持么？ 成就页面是可以点击的

**Comment by xytoki** [comment]
web端圣遗物识别还没完工，整个功能都没有开放。

**Comment by xytoki** [comment]
电脑端如果要使用web端的圣遗物识别的话，可以用莫娜占卜铺的yas-web。
