### ISSUE TITLE
无法登陆同步，邮箱和Microsoft登录都失败

### ISSUE THREAD

**Issue by Abigorangee** [YuehaiTeam/cocogoat#99]
本来以为是服务器的问题……结果一直不行，大概两周左右了，输入邮箱可以接收到邮件，点击显示验证成功，但是返回椰羊还是没登录。Microsoft也一样，登录后没反应，列表始终空荡荡的，没有任何报错，删除离线数据 强制更新离线数据也没用

![image](https://github.com/YuehaiTeam/cocogoat/assets/102571587/db0c11c0-5814-4044-900c-7a243f71bbf8)
![image](https://github.com/YuehaiTeam/cocogoat/assets/102571587/8166958e-b0c6-40fd-83a7-aedfb4896032)

**Comment by CharerChou** [comment]
加一，解决了吗

**Comment by Abigorangee** [comment]
> 加一，解决了吗

解决了。你先试试进入隐私模式（ctrl+shift+N）看看能不能登录椰羊，可以的话回到正常模式，先导出备份你的成就，然后删除网页cookie，删除页面缓存，删除所有记录，重启电脑后，就可以登录了，先登录再导入记录。大概情况就是 得先把现有记录全部清除掉才能登录，原因未知。

**Comment by xiaodao66** [comment]
> > 加一，解决了吗
> 
> 解决了。你先试试进入隐私模式（ctrl+shift+N）看看能不能登录椰羊，可以的话回到正常模式，先导出备份你的成就，然后删除网页cookie，删除页面缓存，删除所有记录，重启电脑后，就可以登录了，先登录再导入记录。大概情况就是 得先把现有记录全部清除掉才能登录，原因未知。

依旧无法登录

**Comment by Abigorangee** [comment]
> > > 加一，解决了吗
> > 
> > 
> > 解决了。你先试试进入隐私模式（ctrl+shift+N）看看能不能登录椰羊，可以的话回到正常模式，先导出备份你的成就，然后删除网页cookie，删除页面缓存，删除所有记录，重启电脑后，就可以登录了，先登录再导入记录。大概情况就是 得先把现有记录全部清除掉才能登录，原因未知。
> 
> 依旧无法登录

清空页面所有记录，删除浏览器缓存，先别导入，在全空的状态下试着登录，能登录上再恢复记录。这一切的前提建立在隐私模式（ctrl+shift+N）能正常登录但常规模式无法登陆。
